name: "Análise de Vulnerabilidades Flutter"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 0 * * 1'  # Executa à meia-noite nas segundas-feiras

jobs:
  flutter-security-audit:
    name: Auditoria de Segurança Flutter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/sustenta_bag_application
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Instalar dependências
        run: flutter pub get
        
      - name: Verificar vulnerabilidades com dependency_validator
        run: |
          echo "### Instalando ferramentas de análise" >> $GITHUB_STEP_SUMMARY
          flutter pub global activate dependency_validator
          
          echo "### Verificando dependências com dependency_validator" >> $GITHUB_STEP_SUMMARY
          flutter pub global run dependency_validator:dependency_validator || true
          
          echo "### Verificando vulnerabilidades do Package Verifier API" >> $GITHUB_STEP_SUMMARY
          flutter pub global activate pana
          flutter pub global run pana . --json > pana-report.json || true
          
          # Extrair informações de dependências
          cat pana-report.json | grep -o '"has_newer_version"' | wc -l > vuln_count.txt
          OUTDATED_COUNT=$(cat vuln_count.txt)
          
          echo "Resultados da análise:" >> $GITHUB_STEP_SUMMARY
          echo "- Pacotes desatualizados: $OUTDATED_COUNT" >> $GITHUB_STEP_SUMMARY
          
          if [ $OUTDATED_COUNT -gt 0 ]; then
            echo "⚠️ **Atenção**: Pacotes desatualizados detectados" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ Todos os pacotes estão na versão mais recente" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Verificar dependências desatualizadas
        run: |
          echo "### Pacotes desatualizados" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          flutter pub outdated --no-dev-dependencies > outdated.txt || true
          cat outdated.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
          # Contar dependências desatualizadas por tipo
          RESOLVABLE_COUNT=$(cat outdated.txt | grep -c "^[^!].*resolvable")
          RESOLVED_COUNT=$(cat outdated.txt | grep -c "^!.*")
          
          echo "Estatísticas de dependências:" >> $GITHUB_STEP_SUMMARY
          echo "- Dependências que podem ser atualizadas: $RESOLVABLE_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Dependências desatualizadas com restrições: $RESOLVED_COUNT" >> $GITHUB_STEP_SUMMARY
          
          if [ $RESOLVABLE_COUNT -gt 0 ]; then
            echo "⚠️ **Recomendação**: Execute 'flutter pub upgrade' para resolver $RESOLVABLE_COUNT dependências" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Verificar vulnerabilidades conhecidas
        run: |
          echo "### Verificando vulnerabilidades conhecidas" >> $GITHUB_STEP_SUMMARY
          
          # Lista de pacotes conhecidos com vulnerabilidades
          # (Esta é uma lista de exemplo - mantenha atualizada com pacotes vulneráveis)
          VULNERABLE_PACKAGES=(
            "http:<0.13.0:Vulnerabilidade de segurança com redirecionamentos"
            "crypto:<3.0.0:Vulnerabilidades criptográficas conhecidas"
            "shared_preferences:<2.0.0:Problemas de segurança no armazenamento"
            "url_launcher:<6.0.0:Vulnerabilidade de validação de URL"
            "webview_flutter:<2.0.0:Vulnerabilidades de segurança de WebView"
            "path_provider:<2.0.0:Problemas de segurança no acesso a arquivos"
          )
          
          VULNERABILITIES_FOUND=0
          HIGH_VULNERABILITIES=0
          
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "Analisando pubspec.lock para vulnerabilidades conhecidas:" >> $GITHUB_STEP_SUMMARY
          
          for package_info in "${VULNERABLE_PACKAGES[@]}"; do
            # Separar informações do pacote (nome:versão:descrição)
            IFS=':' read -r PKG_NAME PKG_VERSION PKG_DESCRIPTION <<< "$package_info"
            
            if grep -q "$PKG_NAME:" pubspec.lock; then
              CURRENT_VERSION=$(grep -A 3 "$PKG_NAME:" pubspec.lock | grep "version:" | sed 's/.*version: "\(.*\)".*/\1/')
              if [ ! -z "$CURRENT_VERSION" ]; then
                if [[ $PKG_VERSION == \<* ]]; then
                  # Remover o "<" para comparação numérica
                  SAFE_VERSION=$(echo $PKG_VERSION | cut -c2-)
                  if [ "$(printf '%s\n' "$SAFE_VERSION" "$CURRENT_VERSION" | sort -V | head -n1)" = "$CURRENT_VERSION" ]; then
                    echo "⚠️ Vulnerabilidade: $PKG_NAME versão $CURRENT_VERSION ($PKG_DESCRIPTION)" >> $GITHUB_STEP_SUMMARY
                    echo "   Recomendação: Atualizar para $SAFE_VERSION ou superior" >> $GITHUB_STEP_SUMMARY
                    VULNERABILITIES_FOUND=$((VULNERABILITIES_FOUND+1))
                    HIGH_VULNERABILITIES=$((HIGH_VULNERABILITIES+1))
                  fi
                fi
              fi
            fi
          done
          
          # Verificar pacotes de terceiros potencialmente inseguros
          SUSPICIOUS_PACKAGES=$(grep -l "verified: false" pubspec.lock || true)
          if [ ! -z "$SUSPICIOUS_PACKAGES" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "⚠️ Pacotes não verificados pelo pub.dev (possível risco de segurança):" >> $GITHUB_STEP_SUMMARY
            UNVERIFIED_COUNT=$(echo "$SUSPICIOUS_PACKAGES" | wc -l)
            VULNERABILITIES_FOUND=$((VULNERABILITIES_FOUND+UNVERIFIED_COUNT))
            
            for pkg in $SUSPICIOUS_PACKAGES; do
              PKG_NAME=$(basename "$pkg" .yaml)
              echo "- $PKG_NAME: Não verificado pelo pub.dev" >> $GITHUB_STEP_SUMMARY
            done
          fi
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          
          echo "Resumo de vulnerabilidades:" >> $GITHUB_STEP_SUMMARY
          echo "- Total: $VULNERABILITIES_FOUND" >> $GITHUB_STEP_SUMMARY
          echo "- Alta severidade: $HIGH_VULNERABILITIES" >> $GITHUB_STEP_SUMMARY
          
          if [ $HIGH_VULNERABILITIES -gt 0 ]; then
            echo "⚠️ **Alerta**: $HIGH_VULNERABILITIES vulnerabilidades de alta severidade encontradas!" >> $GITHUB_STEP_SUMMARY
            echo "Recomendação: Atualize os pacotes vulneráveis imediatamente" >> $GITHUB_STEP_SUMMARY
          elif [ $VULNERABILITIES_FOUND -gt 0 ]; then
            echo "⚠️ **Atenção**: $VULNERABILITIES_FOUND possíveis vulnerabilidades encontradas" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ Nenhuma vulnerabilidade conhecida encontrada!" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Analisar qualidade de código e segurança
        run: |
          echo "### Analisando qualidade de código" >> $GITHUB_STEP_SUMMARY
          
          # Contar alertas de analisador Dart 
          flutter analyze --no-fatal-infos > analyze-report.txt || true
          
          # Contar alertas por tipo
          ERROR_COUNT=$(grep -c "error •" analyze-report.txt || echo 0)
          WARNING_COUNT=$(grep -c "warning •" analyze-report.txt || echo 0)
          INFO_COUNT=$(grep -c "info •" analyze-report.txt || echo 0)
          
          echo "Resultados da análise estática:" >> $GITHUB_STEP_SUMMARY
          echo "- Erros: $ERROR_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Avisos: $WARNING_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Informações: $INFO_COUNT" >> $GITHUB_STEP_SUMMARY
          
          if [ $ERROR_COUNT -gt 0 ] || [ $WARNING_COUNT -gt 0 ]; then
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat analyze-report.txt | head -n 50 >> $GITHUB_STEP_SUMMARY
            if [ $(cat analyze-report.txt | wc -l) -gt 50 ]; then
              echo "... (saída truncada)" >> $GITHUB_STEP_SUMMARY
            fi
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ Nenhum erro ou aviso detectado na análise estática" >> $GITHUB_STEP_SUMMARY
          fi
          
          # Verificar problemas de segurança comuns em código Flutter/Dart
          SECURITY_PATTERNS=(
            "insecureRandomNumber"
            "usesSharedPreferencesWithoutEncryption"
            "WebView.*setJavaScriptEnabled.*true"
            "clearTextTraffic.*true"
            "usesCleartextTraffic.*true"
            "debuggable.*true"
            "setAllowFileAccess.*true"
          )
          
          SECURITY_ISSUES=0
          echo "### Verificando padrões de código inseguros" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          for pattern in "${SECURITY_PATTERNS[@]}"; do
            FOUND=$(find lib -name "*.dart" -exec grep -l "$pattern" {} \; | wc -l)
            if [ $FOUND -gt 0 ]; then
              echo "⚠️ Encontrado possível problema de segurança: $pattern em $FOUND arquivos" >> $GITHUB_STEP_SUMMARY
              SECURITY_ISSUES=$((SECURITY_ISSUES+FOUND))
            fi
          done
          
          if [ $SECURITY_ISSUES -eq 0 ]; then
            echo "✅ Nenhum padrão de código inseguro detectado" >> $GITHUB_STEP_SUMMARY
          fi
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      
      - name: Gerar relatório final
        run: |
          echo "### 📊 Relatório Final de Segurança" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Este relatório identifica possíveis vulnerabilidades e problemas de segurança no projeto Flutter." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### 📝 Recomendações" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "1. **Mantenha dependências atualizadas** executando regularmente `flutter pub upgrade`" >> $GITHUB_STEP_SUMMARY
          echo "2. **Revise o uso de WebViews** para garantir configurações seguras" >> $GITHUB_STEP_SUMMARY
          echo "3. **Use armazenamento seguro** como `flutter_secure_storage` para dados sensíveis" >> $GITHUB_STEP_SUMMARY
          echo "4. **Configure corretamente TLS/HTTPS** e evite tráfego não criptografado" >> $GITHUB_STEP_SUMMARY
          echo "5. **Execute esta análise de vulnerabilidade regularmente**" >> $GITHUB_STEP_SUMMARY